pool:
  vmImage: 'Ubuntu 18.04'

variables:
  imageName: 'registry.baystation12.net/baystation12:latest'

steps:
- script: git clone https://github.com/Baystation12/custom-items
  displayName: 'clone custom items'

- task: DownloadSecureFile@1
  name: libbyond
  inputs:
    secureFile: 'libbyond.so'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'cp $(libbyond.secureFilePath) . && echo "COPY libbyond.so /usr/local/byond/bin/libbyond.so" >> Dockerfile'

- task: Docker@0
  displayName: 'build'
  inputs:
    imageName: '$(imageName)'
    buildArguments: BUILD_ARGS=-Icustom-items/inc.dm

- task: Docker@1
  displayName: 'registry login'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'bs12'
    command: login

- task: Docker@1
  displayName: 'push'
  inputs:
    command: 'push'
    imageName: '$(imageName)'
